### ISSUE TITLE
Pausing/Resuming playback

### ISSUE THREAD

**Issue by vectorvitale** [serebit/autotitan#2] opened 2017-05-25 20:26 UTC
Add the ability to **pause** and **resume** playback of streams

**Comment by serebit** [comment] 2017-05-26 12:13
The last couple commits have added this functionality. Requires testing before the issue can be closed.

**Comment by serebit** [comment] 2017-05-27 03:40
Testing concluded, pausing and resuming now works as intended. Closing issue.

**Closed by serebit** 2017-05-27 03:40 UTC
Labels: enhancement
